version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "requirements/"
    reviewers:
      - "renanvieira"
    schedule:
      interval: "monthly"
    labels:
      - "dependabot"
    ignore:
      - dependency-name: "mock"
        versions: [">4.0.2"]

